version: "3"

services:
  # web:
  #   build: .
  #   ports:
  #     - 3000:3000
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: bookstore
      POSTGRES_PASSWORD: bookstore_pass
      POSTGRES_DB: bookstore
    volumes:
      - bookstore-db:/var/lib/postgresql/data

volumes:
  bookstore-db:
